oracle: 
  username: mailerdev
  password: mailerdev
  url: jdbc:oracle:thin:@172.19.240.215:1521:AMASTDDB01

security:
  jjwt:
    refresh-token-exp-time: 10
    token-header: Authorization
    token-issuer: http://deniz.one
    token-expiration-time: 10
    token-sign-key: hedeleHodoloma
    header-prefix: bearer
    authentication-entry-point: 